version: 2
jobs:
  test:
    docker:
      - image: circleci/node:20
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-npm-{{ checksum "package.json" }}
            - v1-dependencies-npm
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-npm-{{ checksum "package.json" }}
      - run: npm test

  release:
    docker:
      - image: cimg/node:22.7.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-npm-{{ checksum "package.json" }}
            - v1-dependencies-npm
      - run: npm install
      - run: npx semantic-release

workflows:
  version: 2
  test_and_release:
    jobs:
      - test
      - release:
          context:
            - test-runner:npm-release
          requires:
            - test
          filters:
            branches:
              only:
                - master
